# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  # use: wanko # 博客根目录/live2d_models/ 下的目录名
  # use: ./wives/wanko # 相对于博客根目录的路径
  # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  # enable: false
#  scriptFrom: local # 默认
#  pluginRootPath: blog/ # 插件在站点上的根目录(相对路径)
#  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
#  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
#  model:
#    use: live2d-widget-model-ni-j # npm-module package name
#    scale: 1
#    hHeadPos: 0.5
#    vHeadPos: 0.618
#  display:
#    superSample: 2
#    width: 150
#    height: 300
#    position: left
#    hOffset: 0
#    vOffset: -50
#  mobile:
#    show: true
#    scale: 0.5
#  react:
#    opacityDefault: 0.7
#    opacityOnHover: 0.2